apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: belajar-nodejs-dasar
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: default

  source:
    repoURL: https://github.com/fegisucepto/belajar-nodejs-dasar-argocd.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: belajar-nodejs

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
